<%-- 
    Document   : home
    Created on : 21 Aug 2023, 22:42:29
    Author     : mathi
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Je suis la page home du td 04</h1>
        <p>Utilisation de la méthode toString() du bean dans la vue :
            <%
                Beans.Article unBean = (Beans.Article)
                request.getAttribute("message");
                out.println(unBean.toString());
            %>
        </p>
        <p>Generated by JEE</p>
    </body>
</html>
