<%-- 
    Document   : home
    Created on : 21 Aug 2023, 22:42:29
    Author     : mathi
--%>
<%-- Commentaire JSP invisible dans la page transmise au client --%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Je suis la page home du td 04</h1>
        <p>Utilisation de la méthode toString() du bean dans la vue :
            <%
                Beans.Article unBean = (Beans.Article)
                request.getAttribute("message");
                out.println(unBean.toString());
            %>
        </p>
        <jsp:useBean id="alphonse" class="Beans.Personne">
            <jsp:setProperty name="alphonse" property="prenom" value="" />
        </jsp:useBean>
        <p><jsp:getProperty name="alphonse" property="prenom" /></p>
        <p>EL: ${!empty alphonse.prenom ? alphonse.prenom: "Précisez un nom"}</p>
        <p>Generated by JEE</p>
    </body>
</html>
